@startuml architecture-physique

title <size:22>**Architecture physique (déploiement) — EspritMarket**</size>

left to right direction

skinparam dpi 150
skinparam shadowing false
skinparam defaultFontName "Segoe UI"
skinparam rectangleRoundCorner 12
skinparam packageRectangleRoundCorner 18
skinparam ArrowFontSize 12
skinparam linetype polyline

skinparam rectangle {
  BackgroundColor #FFFFFF
  BorderColor #333333
}

actor "Poste client\nNavigateur" as Client

rectangle "**Eureka**\nSpring Cloud Netflix\n<b>:8761</b>" as EU #EFEFEF

package "Serveurs applicatifs (microservices)" #DFF2F0 {
  rectangle "**SRV**\nSpring Boot\n<b>:8082</b>" as SRV
  rectangle "**marketplace**\nSpring Boot\n<b>:8083</b>" as MKT
  rectangle "**Delivery**\nSpring Boot\n<b>:8084</b>" as DEL
  SRV -[hidden]down-> MKT
  MKT -[hidden]down-> DEL
}

database "Serveur PostgreSQL" #FDEBD2 {
  database "**awd-Delivery**" as AWDDB
}

Client -down-> SRV : HTTP
Client -down-> MKT : HTTP
Client -down-> DEL : HTTP

SRV .up.> EU : enregistrement
MKT .up.> EU : enregistrement
DEL .up.> EU : enregistrement

DEL -right-> AWDDB : JDBC

@enduml
